#!/bin/bash

echo "Starting Pink pi GUI install "
apt-get update --yes
apt-get upgrade --yes
apt-get update --yes

#remove current version of openSSL

echo "***Reomving old verision of openSSL"
apt-get remove openssl --yes
apt-get remove libssl-dev --yes

#Add jessie-backport sources

apt-get install dirmngr --yes
apt-get -y install debian-keyring debian-archive-keyring
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
echo "deb-src http://ftp.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/jessie-backports.list
apt-get update

#build openSSL

cd /home/pi
sudo -u pi mkdir deps
cd deps
apt-get source openssl/jessie-backports
cd openssl-1.0.2l
./config --prefix="/home/pi/openssl/" shared enable-ec enable-ecdh enable-ecdsa -lanl -ldl
make
make install

#Building BerkleyDB

cd /home/pi
cd deps
sudo -u pi wget http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
tar -xzvf db-4.8.30.tar.gz db-4.8.30
cd db-4.8.30/build_unix/
sudo -u pi ../dist/configure --enable-cxx --enable-shared
make
make install

apt-get install autoconf libevent-dev libtool libssl-dev libboost-all-dev libminiupnpc-dev libdb++-dev libzmq3-dev libdb5.3++-dev build-essential autotools-dev pkg-config qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools libqrencode-dev git p7zip --yes

#Building Pinkcoin

echo "creating directory /pi/pink"
sudo -u pi mkdir /home/pi/pink
cd /home/pi/pink
echo "starting git clone"
sudo -u pi git clone https://github.com/Pink2Dev/Pink2.git
cd /home/pi/pink/Pink2
echo "starting qmake"
sudo -u pi qmake "USE_QRCODE=1" "USE_UPNP=1" "OPENSSL_INCLUDE_PATH=/home/pi/openssl/include" "OPENSSL_LIB_PATH=/home/pi/openssl/lib" "BDB_INCLUDE_PATH=/usr/local/BerkeleyDB.4.8/include" "BDB_LIB_PATH=/usr/local/BerkeleyDB.4.8/lib"
echo "starting make"
sudo -u pi make

#Adding desktop shortcut

sudo -u pi touch /home/pi/Desktop/pinkcoin-qt.desktop

{
        echo '[Desktop Entry]'
        echo 'Name=Pinkcoin-QT'
        echo 'Comment=Pinkcoin Core GUI'
        echo 'Exec=env LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/BerkeleyDB.4.8/lib:/home/pi/openssl/lib" /home/pi/pink/Pink2/Pinkcoin-Qt'
        echo 'Type=Application'
        echo 'Encoding=UTF-8'  
        echo 'Terminal=false'
        echo 'Categories=None'
} >> /home/pi/Desktop/pinkcoin-qt.desktop

echo "You should have a working desktop icon now, thank me @ my pinkcoinaddress : 2Zm6fb4dwWZ8xYKp41vMwiF7WtfmHahWUj";
